// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_BrewingScreen_screen_init(void)
{
ui_BrewingScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_BrewingScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_BrewingScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Background);
ui_object_set_themeable_style_property(ui_BrewingScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Background);

ui_BrewGraphBack = lv_chart_create(ui_BrewingScreen);
lv_obj_set_width( ui_BrewGraphBack, 320);
lv_obj_set_height( ui_BrewGraphBack, 200);
lv_chart_set_type( ui_BrewGraphBack, LV_CHART_TYPE_LINE);
lv_chart_set_point_count( ui_BrewGraphBack, 360);
lv_chart_set_range( ui_BrewGraphBack, LV_CHART_AXIS_PRIMARY_Y, 0, 10);
lv_chart_set_div_line_count( ui_BrewGraphBack, 11, 10);
lv_chart_set_axis_tick( ui_BrewGraphBack, LV_CHART_AXIS_PRIMARY_X, 100, 5, 10, 2, false, 50);
lv_chart_set_axis_tick( ui_BrewGraphBack, LV_CHART_AXIS_PRIMARY_Y, -20, -10, 6, 5, true, 50);
lv_chart_set_axis_tick( ui_BrewGraphBack, LV_CHART_AXIS_SECONDARY_Y, -30, -10, 5, 10, true, 25);
ui_object_set_themeable_style_property(ui_BrewGraphBack, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Background);
ui_object_set_themeable_style_property(ui_BrewGraphBack, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Background);
lv_obj_set_style_border_color(ui_BrewGraphBack, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_BrewGraphBack, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_line_color(ui_BrewGraphBack, lv_color_hex(0x404076), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_line_opa(ui_BrewGraphBack, 100, LV_PART_MAIN| LV_STATE_DEFAULT);


lv_obj_set_style_size(ui_BrewGraphBack, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_line_color(ui_BrewGraphBack, lv_color_hex(0x767676), LV_PART_TICKS | LV_STATE_DEFAULT );
lv_obj_set_style_line_opa(ui_BrewGraphBack, 100, LV_PART_TICKS| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_BrewGraphBack, lv_color_hex(0x00FF94), LV_PART_TICKS | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BrewGraphBack, 255, LV_PART_TICKS| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_BrewGraphBack, LV_TEXT_ALIGN_AUTO, LV_PART_TICKS| LV_STATE_DEFAULT);

ui_BrewGraph = lv_chart_create(ui_BrewingScreen);
lv_obj_set_width( ui_BrewGraph, 320);
lv_obj_set_height( ui_BrewGraph, 200);
lv_chart_set_type( ui_BrewGraph, LV_CHART_TYPE_LINE);
lv_chart_set_point_count( ui_BrewGraph, 360);
lv_chart_set_range( ui_BrewGraph, LV_CHART_AXIS_SECONDARY_Y, 0, 1000);
lv_chart_set_div_line_count( ui_BrewGraph, 11, 10);
lv_chart_set_axis_tick( ui_BrewGraph, LV_CHART_AXIS_PRIMARY_X, 100, 5, 10, 2, false, 50);
lv_chart_set_axis_tick( ui_BrewGraph, LV_CHART_AXIS_PRIMARY_Y, -20, -10, 6, 5, false, 50);
lv_chart_set_axis_tick( ui_BrewGraph, LV_CHART_AXIS_SECONDARY_Y, -30, -10, 5, 10, false, 25);
lv_obj_set_style_bg_color(ui_BrewGraph, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BrewGraph, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_BrewGraph, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_BrewGraph, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_BrewGraph, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_BrewGraph, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_line_color(ui_BrewGraph, lv_color_hex(0x404076), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_line_opa(ui_BrewGraph, 0, LV_PART_MAIN| LV_STATE_DEFAULT);


lv_obj_set_style_size(ui_BrewGraph, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_line_color(ui_BrewGraph, lv_color_hex(0x767676), LV_PART_TICKS | LV_STATE_DEFAULT );
lv_obj_set_style_line_opa(ui_BrewGraph, 0, LV_PART_TICKS| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_BrewGraph, lv_color_hex(0x00FF94), LV_PART_TICKS | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BrewGraph, 255, LV_PART_TICKS| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_BrewGraph, LV_TEXT_ALIGN_CENTER, LV_PART_TICKS| LV_STATE_DEFAULT);

ui_closeBrewScreenButton = lv_btn_create(ui_BrewingScreen);
lv_obj_set_width( ui_closeBrewScreenButton, 35);
lv_obj_set_height( ui_closeBrewScreenButton, 36);
lv_obj_set_x( ui_closeBrewScreenButton, 114 );
lv_obj_set_y( ui_closeBrewScreenButton, -95 );
lv_obj_set_align( ui_closeBrewScreenButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_closeBrewScreenButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_closeBrewScreenButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_closeBrewScreenButton, lv_color_hex(0xB80000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_closeBrewScreenButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3 = lv_label_create(ui_closeBrewScreenButton);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"x");

ui_timeLabel = lv_label_create(ui_BrewingScreen);
lv_obj_set_width( ui_timeLabel, lv_pct(40));
lv_obj_set_height( ui_timeLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_timeLabel, 0 );
lv_obj_set_y( ui_timeLabel, 5 );
lv_obj_set_align( ui_timeLabel, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_timeLabel,"00:00");
lv_obj_set_style_text_color(ui_timeLabel, lv_color_hex(0x0AF291), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_timeLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_timeLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_timeLabel, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel1 = lv_obj_create(ui_BrewingScreen);
lv_obj_set_width( ui_Panel1, 320);
lv_obj_set_height( ui_Panel1, 35);
lv_obj_set_align( ui_Panel1, LV_ALIGN_BOTTOM_MID );
lv_obj_set_flex_flow(ui_Panel1,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Panel1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_Panel1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Background);
ui_object_set_themeable_style_property(ui_Panel1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Background);
lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pLabel = lv_label_create(ui_Panel1);
lv_obj_set_width( ui_pLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_pLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_pLabel, -10 );
lv_obj_set_y( ui_pLabel, 0 );
lv_obj_set_align( ui_pLabel, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_pLabel,"P:");
lv_obj_set_style_text_color(ui_pLabel, lv_color_hex(0x00A0FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_pLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pValueLabel = lv_label_create(ui_Panel1);
lv_obj_set_width( ui_pValueLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_pValueLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_pValueLabel, 5 );
lv_obj_set_y( ui_pValueLabel, 0 );
lv_obj_set_align( ui_pValueLabel, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_pValueLabel,"9.2");
lv_obj_set_style_text_color(ui_pValueLabel, lv_color_hex(0x00A0FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_pValueLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_fLabel = lv_label_create(ui_Panel1);
lv_obj_set_width( ui_fLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_fLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_fLabel, 35 );
lv_obj_set_y( ui_fLabel, 0 );
lv_obj_set_align( ui_fLabel, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_fLabel,"F:");
lv_obj_set_style_text_color(ui_fLabel, lv_color_hex(0xFCE508), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_fLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_fValueLabel = lv_label_create(ui_Panel1);
lv_obj_set_width( ui_fValueLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_fValueLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_fValueLabel, 50 );
lv_obj_set_y( ui_fValueLabel, 0 );
lv_obj_set_align( ui_fValueLabel, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_fValueLabel,"3.2");
lv_obj_set_style_text_color(ui_fValueLabel, lv_color_hex(0xFCE508), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_fValueLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wLabel = lv_label_create(ui_Panel1);
lv_obj_set_width( ui_wLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wLabel, 80 );
lv_obj_set_y( ui_wLabel, 0 );
lv_obj_set_align( ui_wLabel, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_wLabel,"W:");
lv_obj_set_style_text_color(ui_wLabel, lv_color_hex(0x03C2C2), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_wLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wValueLabel = lv_label_create(ui_Panel1);
lv_obj_set_width( ui_wValueLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wValueLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wValueLabel, 100 );
lv_obj_set_y( ui_wValueLabel, 0 );
lv_obj_set_align( ui_wValueLabel, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_wValueLabel,"32.5");
lv_obj_set_style_text_color(ui_wValueLabel, lv_color_hex(0x03C2C2), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_wValueLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wPsLabel = lv_label_create(ui_Panel1);
lv_obj_set_width( ui_wPsLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wPsLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wPsLabel, 140 );
lv_obj_set_y( ui_wPsLabel, 0 );
lv_obj_set_align( ui_wPsLabel, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_wPsLabel,"W/s:");
lv_obj_set_style_text_color(ui_wPsLabel, lv_color_hex(0xA001C8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_wPsLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wPsValueLabel = lv_label_create(ui_Panel1);
lv_obj_set_width( ui_wPsValueLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wPsValueLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wPsValueLabel, 175 );
lv_obj_set_y( ui_wPsValueLabel, 0 );
lv_obj_set_align( ui_wPsValueLabel, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_wPsValueLabel,"1.5");
lv_obj_set_style_text_color(ui_wPsValueLabel, lv_color_hex(0xA001C8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_wPsValueLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_tLabel = lv_label_create(ui_Panel1);
lv_obj_set_width( ui_tLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_tLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_tLabel, 200 );
lv_obj_set_y( ui_tLabel, 0 );
lv_obj_set_align( ui_tLabel, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_tLabel,"T:");
lv_obj_set_style_text_color(ui_tLabel, lv_color_hex(0xFD0404), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_tLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_tValueLabel = lv_label_create(ui_Panel1);
lv_obj_set_width( ui_tValueLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_tValueLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_tValueLabel, 215 );
lv_obj_set_y( ui_tValueLabel, 0 );
lv_obj_set_align( ui_tValueLabel, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_tValueLabel,"98.9");
lv_obj_set_style_text_color(ui_tValueLabel, lv_color_hex(0xFD0404), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_tValueLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_closeBrewScreenButton, ui_event_closeBrewScreenButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BrewingScreen, ui_event_BrewingScreen, LV_EVENT_ALL, NULL);

}
