// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_HomeScreen_screen_init(void)
{
ui_HomeScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_HomeScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TabView1 = lv_tabview_create(ui_HomeScreen, LV_DIR_TOP, 50);
lv_obj_set_width( ui_TabView1, 320);
lv_obj_set_height( ui_TabView1, 240);
lv_obj_set_align( ui_TabView1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_TabView1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_TabView1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Background);
ui_object_set_themeable_style_property(ui_TabView1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Background);

ui_object_set_themeable_style_property(lv_tabview_get_tab_btns(ui_TabView1),  LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Foreground);
ui_object_set_themeable_style_property(lv_tabview_get_tab_btns(ui_TabView1),  LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Foreground);
ui_object_set_themeable_style_property(lv_tabview_get_tab_btns(ui_TabView1),  LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Background);
ui_object_set_themeable_style_property(lv_tabview_get_tab_btns(ui_TabView1),  LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Background);

ui_object_set_themeable_style_property(lv_tabview_get_tab_btns(ui_TabView1),  LV_PART_ITEMS| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Foreground);
ui_object_set_themeable_style_property(lv_tabview_get_tab_btns(ui_TabView1),  LV_PART_ITEMS| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Foreground);
ui_object_set_themeable_style_property(lv_tabview_get_tab_btns(ui_TabView1),  LV_PART_ITEMS| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Background);
ui_object_set_themeable_style_property(lv_tabview_get_tab_btns(ui_TabView1),  LV_PART_ITEMS| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Background);

ui_TabPage1 = lv_tabview_add_tab(ui_TabView1, "Home");
lv_obj_clear_flag( ui_TabPage1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_TabPage1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_TabPage1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_TabPage1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_TabPage1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container1 = lv_obj_create(ui_TabPage1);
lv_obj_remove_style_all(ui_Container1);
lv_obj_set_width( ui_Container1, 100);
lv_obj_set_height( ui_Container1, 180);
lv_obj_set_align( ui_Container1, LV_ALIGN_LEFT_MID );
lv_obj_set_flex_flow(ui_Container1,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Container1, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Container1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_flushButton = lv_btn_create(ui_Container1);
lv_obj_set_width( ui_flushButton, 100);
lv_obj_set_height( ui_flushButton, 50);
lv_obj_add_flag( ui_flushButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_flushButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label1 = lv_label_create(ui_flushButton);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"FLUSH");

ui_cleaningButton = lv_btn_create(ui_Container1);
lv_obj_set_width( ui_cleaningButton, 100);
lv_obj_set_height( ui_cleaningButton, 50);
lv_obj_set_align( ui_cleaningButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_cleaningButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_cleaningButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label2 = lv_label_create(ui_cleaningButton);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"Cleaning");

ui_Button1 = lv_btn_create(ui_Container1);
lv_obj_set_width( ui_Button1, 100);
lv_obj_set_height( ui_Button1, 50);
lv_obj_set_align( ui_Button1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_manualBrewLabel = lv_label_create(ui_Button1);
lv_obj_set_width( ui_manualBrewLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_manualBrewLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_manualBrewLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_manualBrewLabel,"Manual\nBrew");
lv_obj_set_style_text_align(ui_manualBrewLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container2 = lv_obj_create(ui_TabPage1);
lv_obj_remove_style_all(ui_Container2);
lv_obj_set_width( ui_Container2, 210);
lv_obj_set_height( ui_Container2, 20);
lv_obj_set_x( ui_Container2, -2 );
lv_obj_set_y( ui_Container2, -80 );
lv_obj_set_align( ui_Container2, LV_ALIGN_RIGHT_MID );
lv_obj_set_flex_flow(ui_Container2,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_Container2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Container2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Container2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Container2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label4 = lv_label_create(ui_Container2);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"Profile: ");
ui_object_set_themeable_style_property(ui_Label4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Foreground);
ui_object_set_themeable_style_property(ui_Label4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Foreground);

ui_profileNameLabel = lv_label_create(ui_Container2);
lv_obj_set_height( ui_profileNameLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_flex_grow( ui_profileNameLabel, 1);
lv_obj_set_align( ui_profileNameLabel, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_profileNameLabel,LV_LABEL_LONG_SCROLL_CIRCULAR);
lv_label_set_text(ui_profileNameLabel,"Loading ...");
ui_object_set_themeable_style_property(ui_profileNameLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Foreground);
ui_object_set_themeable_style_property(ui_profileNameLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Foreground);

ui_Container3 = lv_obj_create(ui_TabPage1);
lv_obj_remove_style_all(ui_Container3);
lv_obj_set_width( ui_Container3, lv_pct(67));
lv_obj_set_height( ui_Container3, lv_pct(85));
lv_obj_set_align( ui_Container3, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_set_flex_flow(ui_Container3,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_text_color(ui_Container3, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Container3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_currentProfileGraph = lv_chart_create(ui_Container3);
lv_obj_set_height( ui_currentProfileGraph, 80);
lv_obj_set_width( ui_currentProfileGraph, lv_pct(100));
lv_obj_set_align( ui_currentProfileGraph, LV_ALIGN_CENTER );
lv_chart_set_type( ui_currentProfileGraph, LV_CHART_TYPE_LINE);
lv_chart_set_axis_tick( ui_currentProfileGraph, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, false, 50);
lv_chart_set_axis_tick( ui_currentProfileGraph, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, false, 50);
lv_chart_set_axis_tick( ui_currentProfileGraph, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, false, 25);
lv_chart_series_t* ui_currentProfileGraph_series_1 = lv_chart_add_series(ui_currentProfileGraph, lv_color_hex(0xDCD923), LV_CHART_AXIS_PRIMARY_Y);
static lv_coord_t ui_currentProfileGraph_series_1_array[] = { 0,10,20,40,80,80,40,20,10,0 };
lv_chart_set_ext_y_array(ui_currentProfileGraph, ui_currentProfileGraph_series_1, ui_currentProfileGraph_series_1_array);
lv_chart_series_t* ui_currentProfileGraph_series_2 = lv_chart_add_series(ui_currentProfileGraph, lv_color_hex(0x0269F6), LV_CHART_AXIS_PRIMARY_Y);
static lv_coord_t ui_currentProfileGraph_series_2_array[] = { 20,20,20,20,15,0 };
lv_chart_set_ext_y_array(ui_currentProfileGraph, ui_currentProfileGraph_series_2, ui_currentProfileGraph_series_2_array);
lv_obj_set_style_radius(ui_currentProfileGraph, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_currentProfileGraph, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_currentProfileGraph, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_currentProfileGraph, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_currentProfileGraph, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_currentProfileGraph, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_currentProfileGraph, 0, LV_PART_MAIN| LV_STATE_DEFAULT);


lv_obj_set_style_size(ui_currentProfileGraph, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_Container6 = lv_obj_create(ui_currentProfileGraph);
lv_obj_remove_style_all(ui_Container6);
lv_obj_set_width( ui_Container6, 210);
lv_obj_set_height( ui_Container6, 15);
lv_obj_set_align( ui_Container6, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_Container6,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container6, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label8 = lv_label_create(ui_Container6);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label8,"Pressure");
lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xFFEB3B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label9 = lv_label_create(ui_Container6);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label9,"Flow");
lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0x0997DB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_tempGauge = lv_arc_create(ui_Container3);
lv_obj_set_width( ui_tempGauge, 70);
lv_obj_set_height( ui_tempGauge, 70);
lv_obj_set_align( ui_tempGauge, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_tempGauge, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_arc_set_range(ui_tempGauge, 0,120);
lv_arc_set_value(ui_tempGauge, 50);
lv_obj_set_style_arc_color(ui_tempGauge, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_tempGauge, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_tempGauge, lv_color_hex(0xFF404F), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_tempGauge, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_tempGauge, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_tempGauge, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_tempGauge, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_tempLabel = lv_label_create(ui_tempGauge);
lv_obj_set_width( ui_tempLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_tempLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_tempLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_tempLabel,"98.7");
ui_object_set_themeable_style_property(ui_tempLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Foreground);
ui_object_set_themeable_style_property(ui_tempLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Foreground);

ui_waterGauge = lv_arc_create(ui_Container3);
lv_obj_set_width( ui_waterGauge, 70);
lv_obj_set_height( ui_waterGauge, 70);
lv_obj_set_align( ui_waterGauge, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_waterGauge, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_arc_set_value(ui_waterGauge, 30);
lv_obj_set_style_arc_color(ui_waterGauge, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_waterGauge, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_waterGauge, lv_color_hex(0x4061FF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_waterGauge, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_waterGauge, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_waterGauge, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_waterGauge, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_waterLabel = lv_label_create(ui_waterGauge);
lv_obj_set_width( ui_waterLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_waterLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_waterLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_waterLabel,"30%");
ui_object_set_themeable_style_property(ui_waterLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Foreground);
ui_object_set_themeable_style_property(ui_waterLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Foreground);

ui_Container5 = lv_obj_create(ui_Container3);
lv_obj_remove_style_all(ui_Container5);
lv_obj_set_width( ui_Container5, 70);
lv_obj_set_height( ui_Container5, 70);
lv_obj_set_align( ui_Container5, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container5,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container5, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Container5, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Container5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_weightLabel = lv_label_create(ui_Container5);
lv_obj_set_width( ui_weightLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_weightLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_weightLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_weightLabel,"0.0g");

ui_tareButton = lv_btn_create(ui_Container5);
lv_obj_set_width( ui_tareButton, 50);
lv_obj_set_height( ui_tareButton, 20);
lv_obj_set_align( ui_tareButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_tareButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_tareButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label7 = lv_label_create(ui_tareButton);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"Tare");

ui_Container4 = lv_obj_create(ui_TabPage1);
lv_obj_remove_style_all(ui_Container4);
lv_obj_set_height( ui_Container4, 20);
lv_obj_set_width( ui_Container4, lv_pct(100));
lv_obj_set_align( ui_Container4, LV_ALIGN_BOTTOM_MID );
lv_obj_set_flex_flow(ui_Container4,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_Container4, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Container4, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Container4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Container4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Container4, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Container4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_uptimeLabel = lv_label_create(ui_Container4);
lv_obj_set_width( ui_uptimeLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_uptimeLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_uptimeLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_uptimeLabel,"00:00:00");

ui_wifiStatusLabel = lv_label_create(ui_Container4);
lv_obj_set_width( ui_wifiStatusLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifiStatusLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_wifiStatusLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_wifiStatusLabel,"Wifi");

ui_TabPage2 = lv_tabview_add_tab(ui_TabView1, "Profiles");

ui_TabPage3 = lv_tabview_add_tab(ui_TabView1, "Settings");

lv_obj_add_event_cb(ui_flushButton, ui_event_flushButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_cleaningButton, ui_event_cleaningButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_tareButton, ui_event_tareButton, LV_EVENT_ALL, NULL);

}
