// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Splash_screen_init(void)
{
ui_Splash = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Splash, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_add_event_cb(ui_Splash, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED, &ui_Splash);
ui_object_set_themeable_style_property(ui_Splash, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Background);
ui_object_set_themeable_style_property(ui_Splash, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Background);

ui_Spinner2 = lv_spinner_create(ui_Splash,1000,90);
lv_obj_set_width( ui_Spinner2, 120);
lv_obj_set_height( ui_Spinner2, 120);
lv_obj_set_align( ui_Spinner2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Spinner2, LV_OBJ_FLAG_CLICKABLE );    /// Flags
ui_object_set_themeable_style_property(ui_Spinner2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR, _ui_theme_color_Background);
ui_object_set_themeable_style_property(ui_Spinner2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_ARC_OPA, _ui_theme_alpha_Background);

ui_object_set_themeable_style_property(ui_Spinner2, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR, _ui_theme_color_Foreground);
ui_object_set_themeable_style_property(ui_Spinner2, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_ARC_OPA, _ui_theme_alpha_Foreground);
lv_obj_set_style_arc_width(ui_Spinner2, 10, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_Label5 = lv_label_create(ui_Splash);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"Steelduino");
lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x27ADDE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

}
