// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TabView1 = lv_tabview_create(ui_Screen1, LV_DIR_TOP, 50);
lv_obj_set_width( ui_TabView1, 316);
lv_obj_set_height( ui_TabView1, 234);
lv_obj_set_align( ui_TabView1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_TabView1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags


ui_TabPage1 = lv_tabview_add_tab(ui_TabView1, "Title 1");

ui_TabPage2 = lv_tabview_add_tab(ui_TabView1, "Title 2");

ui_Chart1 = lv_chart_create(ui_TabPage2);
lv_obj_set_width( ui_Chart1, 300);
lv_obj_set_height( ui_Chart1, 145);
lv_chart_set_type( ui_Chart1, LV_CHART_TYPE_LINE);
lv_chart_set_axis_tick( ui_Chart1, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
lv_chart_set_axis_tick( ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
lv_chart_set_axis_tick( ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
lv_chart_series_t* ui_Chart1_series_1 = lv_chart_add_series(ui_Chart1, lv_color_hex(0x808080), LV_CHART_AXIS_PRIMARY_Y);
static lv_coord_t ui_Chart1_series_1_array[] = { 0,10,20,40,80,80,40,20,10,0 };
lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_1, ui_Chart1_series_1_array);



ui_TabPage3 = lv_tabview_add_tab(ui_TabView1, "Title 3");

ui_Switch1 = lv_switch_create(ui_TabPage3);
lv_obj_set_width( ui_Switch1, 50);
lv_obj_set_height( ui_Switch1, 25);
lv_obj_set_x( ui_Switch1, -118 );
lv_obj_set_y( ui_Switch1, -26 );
lv_obj_set_align( ui_Switch1, LV_ALIGN_CENTER );


ui_Checkbox1 = lv_checkbox_create(ui_TabPage3);
lv_obj_set_width( ui_Checkbox1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Checkbox1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Checkbox1, -92 );
lv_obj_set_y( ui_Checkbox1, -66 );
lv_obj_set_align( ui_Checkbox1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Checkbox1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags


}
