// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

// SCREEN: ui_Splash
void ui_Splash_screen_init(void);
extern lv_obj_t *ui_Splash;
extern lv_obj_t *ui_Spinner2;
extern lv_obj_t *ui_Label5;
// SCREEN: ui_HomeScreen
void ui_HomeScreen_screen_init(void);
extern lv_obj_t *ui_HomeScreen;
extern lv_obj_t *ui_TabView1;
extern lv_obj_t *ui_TabPage1;
extern lv_obj_t *ui_Container1;
void ui_event_flushButton( lv_event_t * e);
extern lv_obj_t *ui_flushButton;
extern lv_obj_t *ui_Label1;
void ui_event_cleaningButton( lv_event_t * e);
extern lv_obj_t *ui_cleaningButton;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Button1;
extern lv_obj_t *ui_manualBrewLabel;
extern lv_obj_t *ui_Container2;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_profileNameLabel;
extern lv_obj_t *ui_Container3;
extern lv_obj_t *ui_currentProfileGraph;
extern lv_obj_t *ui_Container6;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_Label9;
extern lv_obj_t *ui_tempGauge;
extern lv_obj_t *ui_tempLabel;
extern lv_obj_t *ui_waterGauge;
extern lv_obj_t *ui_waterLabel;
extern lv_obj_t *ui_Container5;
extern lv_obj_t *ui_weightLabel;
void ui_event_tareButton( lv_event_t * e);
extern lv_obj_t *ui_tareButton;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_Container4;
extern lv_obj_t *ui_uptimeLabel;
extern lv_obj_t *ui_wifiStatusLabel;
extern lv_obj_t *ui_TabPage2;
extern lv_obj_t *ui_TabPage3;
// SCREEN: ui_BrewingScreen
void ui_BrewingScreen_screen_init(void);
void ui_event_BrewingScreen( lv_event_t * e);
extern lv_obj_t *ui_BrewingScreen;
extern lv_obj_t *ui_BrewGraphBack;
extern lv_obj_t *ui_BrewGraph;
void ui_event_closeBrewScreenButton( lv_event_t * e);
extern lv_obj_t *ui_closeBrewScreenButton;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_timeLabel;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_pLabel;
extern lv_obj_t *ui_pValueLabel;
extern lv_obj_t *ui_fLabel;
extern lv_obj_t *ui_fValueLabel;
extern lv_obj_t *ui_wLabel;
extern lv_obj_t *ui_wValueLabel;
extern lv_obj_t *ui_wPsLabel;
extern lv_obj_t *ui_wPsValueLabel;
extern lv_obj_t *ui_tLabel;
extern lv_obj_t *ui_tValueLabel;
// SCREEN: ui_EditProfileScreen
void ui_EditProfileScreen_screen_init(void);
extern lv_obj_t *ui_EditProfileScreen;
extern lv_obj_t *ui____initial_actions0;





void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
